src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVurderingSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt

Dropper (foreløpig) å håndterere caser hvor oppfølgingstilfellet har gått fra å være lenger enn 8 uker til kortere enn 8 uker. Tanken er at det vil være såpass få tilfeller at veileder kan håndtere disse oppgavene ved å sette Oppfylt.

Skipped processing oppfølgingstilfelle not relevant for aktivitetskrav

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVurderingService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingRequestDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt

Oppdaterer status, beskrivelse, veileder-ident som endret og sistEndret-felt for en aktivitetskrav-vurdering med gitt uuid. Skal oppdatere vurderingen i databasen og ut på Kafka.

Veileder-api: Update aktivitetskrav-vurdering

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Dersom det ikke eksisterer aktivitetskrav for oppfølgingstilfellet på person _eller_ eksisterende aktivitetskrav er automatisk oppfylt, men oppfølgingstilfellet ikke lenger gradert: Lag nytt aktivitetskrav.
Ellers: Oppdater eksisterende aktivitetskrav stoppunkt-dato.

Forenklet lag/oppdatere aktivitetskrav

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Dersom en person har blitt vurdert, så blir gradert og så blir 100% sykmeldt igjen så bør personen komme inn igjen i lista til vurdering.
Koden bygger på https://github.com/navikt/isaktivitetskrav/pull/25.

Lag nytt automatisk oppfylt aktivitetskrav hvis vurdert og gradert tilfelle

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Også gjort litt renaming av metoder (presisering, typos) + refaktorering av test.

Automatisk oppfyll "ubehandlet" aktivitetskrav fra tidligere oppfølgingstilfelle når nytt oppfølgingstilfelle > 8 uker

---

src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt

Færre samtidighetskonflikter i syfooversiktsrv i dag, men de forekommer fortsatt. 
Førsøker å forsinke sending av aktivitetskrav til Kafka sånn at det er større sannsynlighet for at oppfølgingstilfellet er ferdig prosessert i syfooversiktsrv før aktivitetskravet kommer.

Delay sending of records to Kafka

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Filter in service after query, queries shouldn't be slow anyway, because no one have a lot of aktivitetskrav. Assuming we're never interested in older aktivitetskrav.

Only return aktivitetskrav with stoppunkt after Arena cutoff

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Endret isVurdert-sjekken slik at aktivitetskrav med status AVVENT ikke blir automatisk oppfylt hvis oppfølgingstilfellet blir gradert. (Personer med aktivitetskrav med status AVVENT skal vises med "aktivt" aktivitetskrav i syfooversikt helt til det er gjort en vurdering)

Avvent is not vurdert

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/util/DateUtil.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Fikser sjekk på om aktivitetskrav gjelder tilfelle til å returnere `true` dersom `tilfelleEnd` (tom-dato) er lik stoppunkt.

Bugfix aktiviteskrav gjelder tilfelle

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskrav.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/main/resources/db/migration/V1_9__add_referanse_tilfellebit_uuid.sql
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Kan være nyttig å lagre denne for å lette feilsøking/analyse av hvilken tilfelle-bit som har ført til at et aktivitetskrav har blitt generert. Feltet vil være null for aktivitetskrav som er opprettet uten oppfølgingstilfelle (dvs av veileder i Modia - f.eks. for utenlandske sykmeldte)

Add referanseTilfelleBitUuid to aktivitetskrav

---

.nais/naiserator-prod.yaml
src/main/resources/cronjob/uuids_ny.json

Må sette noen aktivitetskrav som ble feilaktig automatisk oppfylt ved rydding tilbake til NY.

Add uuids and enable in prod

---

src/main/resources/db/migration/V2_5__delete_wrong_vurdering.sql

https://jira.adeo.no/browse/FAGSYSTEM-284852
Tanken er at veileder kan gå inn å gjøre riktig aktivitetskrav-vurdering etterpå så vi trenger ikke lage script som oppdaterer status til NY i syfooversiktsrv.

Delete aktivitetskrav vurdering made on wrong person

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravMetrics.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt

Vil ha dette inn i grafana - særlig forhåndsvarselet.
Dropper foreløpig typene NY, AUTOMATISK_OPPFYLT og LUKKET, litt usikker på om det er interessant å telle de?

Add metrics to aktivitetskravvurdering that is published to kafka

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt

Flytter denne slik at den bare gjelder AktivitetskravVurderingProducer. Det ble lagt på "linger" her for å forsinke publisering av aktivitetskrav til syfooversikt og unngå samtidighetskonflikt der.

Move linger config to vurdering producer

---

src/main/resources/db/migration/V2_9__delete_wrong_vurdering.sql

Veileder har registrert et korrekt unntak etterpå, så vi trenger bare fjerne den feilregistrerte vurderingen.

Slett feilregistrert vurdering

---

.github/workflows/kafka-aktivitetskrav.yaml
.nais/kafka/aktivitetskrav-varsel.yaml
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVarselProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaAktivitetskravVarselSerializer.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/util/DateUtil.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt

Publiserer aktivitetskrav-varsel-data (journalpostId og document) på egen topic som eSyfo kan konsumere for å vise fram forhåndsvarsel

Add aktivitetskrav-varsel kafka topic and produce

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt

Flyttet varsel-relaterte fra `AktivitetskravService` til `AktivitetskravVarselService` og bruker samtidig denne fra cronjobbene.

Refactor to AktivitetskravVarselService

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Tanken er at APIet også må returnere evt varsel knyttet til en vurdering slik at vi kan vise svar-fristen på forhåndsvarselet i modia:
Pdd hentes denne fra vurderingen, men vi ønsker å heller lagre dette i nytt svar-frist-felt på varselet.

Add varsel to responsedto

---

.nais/kafka/aktivitetskrav-expired-varsel.yaml

Fixes earlier fail of deploy. `{ { kafkaPool } }` is not the same as `{{ kafkaPool }}`🤝

Fix deploy of kafka topic to nais cluster

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Svarfrist for innbyggere og dagen veiledere skal få opp oppgave i oversikten skal begge være 3 uker. Denne PR'en endrer at vi sender utgåtte varsler til veiledere `svarfrist + 1 uke` og sender heller utgåtte varsler til veildere på samme tid som `svarfrist`

IS-1649: Set expired date to same as svarfrist

---

src/main/resources/db/migration/V3_3__delete_wrong_vurdering.sql

Sletter feil vurdering. Den forrige vurderingen var også unntak og tror derfor det blir riktig å bare slette vurderingen uten å endre status for `aktivitetskrav`.

IS-1633: Add migration script to delete vurdering

---

src/main/kotlin/no/nav/syfo/application/kafka/KafkaTask.kt

Her har det sneket seg inn en bug mens jeg jobbet med identhendelser i fjor. Trodde sikkert at launchKafkaTask var spesifikk og ikke generell, og hardkodet derfor topicet. Heldigvis gjør vi vel ingen unsubscribe noen andre steder enn i identhendelse-consumeren, men hvis man på sikt vil gjøre noe sånt, så er det dumt om den kobler seg på feil topic slik den gamle koden tillater.
Se også: https://github.com/navikt/syfooversiktsrv/pull/317

IS-1652: Use correct topic when resubscribing

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Slår på i prod/fjerner toggle for publisering av utgåtte varsler, som `ispersonoppgave` bruker for å lage `vurder_stans`-oppgaver.

IS-1581: Remove toggle for expired varsel

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt

- Legger til å filtrere ut varsler som er "håndtert" når vi henter varsler som er utgått altså tidspunktet innbygger har å svare på varselet og når veileder får varsel opp i sin egen oversikt over "oppgaver".
- Legger også til en test som lager 3 forhåndsvarsler der man etterpå vurderer 2 av de til `OPPFYLT` of `UNNTAK`.
`Handled`/`Håndtert` = Når man som veileder mellom varselet har blitt laget og tiden før det har gått ut har satt en ny vurdering på aktivitetskravet som er `OPPFYLT` eller `UNNTAK`. Da har man håndtert det gjeldende varselet og de trenger ikke å få dette opp i sin oversikt.

IS-1669: Add filtering out handled varsler + tests

---

src/main/resources/db/migration/V3_5__add_original_aktivitetskrav_uuid.sql

- Legger til ny kolonne i `aktivietskrav` database som skal holde en uuid referanse til originaltilfellet av aktivitetskravet slik at vi har kontroll på hvilke vurderingsrunder som gjøres innenfor samme sykefraværstilfelle.
- Bare å komme med forslag til navn på denne kolonnen🙏

IS-1749: Add migration script for new column

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVarsel.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Under Historikk i aktivitetskrav-siden viser vi nå friteksten som sendes ut sammen med et forhåndsvarsel, men tanken er også at veileder skal kunne se hele brevet som ble sendt. Da må vi sende med DocumentComponent, og vise denne frem. Det blir litt lignende logikk som i dialogmeldinger 👍🏼

IS-1601: Send varsel-document in response for aktivitetskrav get-call

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/NewAktivitetskravDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravMetrics.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/main/resources/db/migration/V3_5__add_original_aktivitetskrav_uuid.sql
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

- Legger til endepunkt for å lage en ny aktivitetskrav ressurs `POST /aktivitetskrav`. Har tenkt at dette skal gjelde både for når vi lager ny aktivitetskrav ressurs første gang (uten at det er generert et oppfølgningstilfelle, og når man som veileder går i gang med en ny runde med vurderinger. Det som skiller disse er om det sendes med en request body til endepunktet som inneholder det forrige aktivitetskravet's `UUID`
- Har også refaktorert litt i `Aktivitetskrav` ettersom jeg har blitt litt forvirret over hva `tilfelle` er og ikke skjønt at dette er et `oppfølgningstilfelle`. Tenker også at det er en fordel at vi har litt færre konstruktør metoder, og putter inn logikken for hvordan et `Aktivitetskrav` lages inn i konstruktørmetoden og at dette ikke lever utenfor 😊

IS-1749: Add create new aktivitetskrav endpoint

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Fjerner endepunkt som ikke lenger er i bruk når https://github.com/navikt/syfomodiaperson/pull/1069 er merget. Erstattet av endepunkt for å opprette aktivitetskrav med status `NY_VURDERING`.

IS-1778: Fjerner endepunkt for å opprette og vurdere aktivitetskrav

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravStatus.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Når vi oppretter nytt aktivitetskrav og man har angitt `previousAktivitetskravUuid` bør vi validere at dette er et aktivitetskrav som eksisterer og at det er i sluttilstand.
La også til noen ekstra tester og litt forenkling av tilstandsjekken ifm forhåndsvarsel.

IS-1777: Validate previous aktivitetskrav exists and in final state

---

src/main/resources/db/migration/V3_6__delete_wrong_vurdering.sql

Also set status of aktivitetskrav to NY, delete ny_vurdering.
This will allow the veileder to make a new vurdering with correct input.
We assume the ny_vurdering is not needed and was only created because the veileder wanted to correct their mistake.

Delete vurdering with wrong begrunnelse

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/DokarkivMock.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/MockHttpClient.kt

If api receives an kesternReferanseId that is already stored, it will return 409 Conflict with the existing JournalPost as body.
We want to fail when we get 409 becuase we don't want to journalføre the same varsel more than once.

IS-1867: Add eksternReferanseId to journalpostRequest

---

.nais/naiserator-prod.yaml

Skrur av denne cronjobben i prod siden den kjører en "tung" sql i databasen som ikke skal eller vil gi noe resultat.

Turn off outdated aktivitetskrav cronjob in prod

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

The first given date is not counted when adding weeks, but when we calculate duration of tilfelle it is.
When tilfelle is exactly 56 days long, stoppunkt will be after the tilfelle end date.
This causes us to make a new aktivitetskrav when we get an updated tilfelle on kafka with the same end date.
This change makes the stoppunkt date count the first date of the tilfelle like we do when calculating the tilfelle length.

S-1938: Subtract one day from stoppunkt date

---

src/main/resources/db/migration/V4_0__fix_stoppunkt.sql

See https://github.com/navikt/isaktivitetskrav/pull/194
This will change all stoppunkt created after we added "antallSykedager" so they align with how we calculate tilfelle duration.
Now they will also be the same as new aktivitetskrav will be with the previously added stoppunkt logic.
Now we avoid creating even more aktivitetskrav for updated tilfeller with same duration.

IS-1938: change some stoppunkt to one day earlier

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/DocumentComponentDTO.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/ForhandsvarselPdfDTO.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/VurderingPdfDTO.kt
src/test/kotlin/no/nav/syfo/client/pdfgen/ForhandsvarselPdfDTOSpek.kt
src/test/kotlin/no/nav/syfo/client/pdfgen/PdfGenClientSpek.kt
src/test/kotlin/no/nav/syfo/client/pdfgen/VurderingPdfDTOSpek.kt

Lagt til tilsvarende håndtering vi har i andre apper for å filtrere ut ulovlig tegn fra document-component-text før pdf-generering.

IS-1943: remove illegal chars from document component texts before pdgen

---

src/main/resources/db/migration/V4_2__delete_wrong_vurdering.sql

Sletter feilregistrert unntak på person. Veileder har startet ny vurdering i etterkant så tror ikke det trengs noen oppdatering av aktivitetskravet eller sletting på eSyfo sin side.

IS-2018: Delete vurdering

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt

Nøkkelen vi logger i dag lagres ikke i databasen, så det er vanskelig å finne det som feilet.
Derfor logger vi nå også uuid for aktivitetskravet og siste vurdering.

Log uuids when sending to kafka fails

---

src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClient.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivMetric.kt
src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/DokarkivMock.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/MockUtils.kt

409 fra Dokarkiv betyr at journalpost allerede er opprettet og vi kan håndtere dette ved å lagre journalpostIden vi får fra responsen.

IS-2267: Handle 409 from dokarkiv

---

src/main/kotlin/no/nav/syfo/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt

Fikset bug som gjorde at vi oppdaterte gamle aktivitetskrav med stoppunkt-dato før Arena-cutoff (disse skal ha blitt vurdert i Arena og skal ikke dukke opp i Modia). 
Oppdateringen ble sendt på Kafka og førte til at personen ble satt til aktiv i oversikten. 
Fant 293 tilfeller i oversikten hvor det nye flagget `is_aktiv_aktivitetskrav_vurdering` var satt til `true`, men personen skulle ikke ha hatt aktivt aktivitetskrav basert på logikken for de "gamle" feltene. Retter opp disse når vi migrerer aktivitetskrav-dataene i oversikten.

IS-2596: Do not update aktivitetskrav with stoppunkt before arena cutoff

---

gradle.properties
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/main/kotlin/no/nav/syfo/util/DateUtil.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Dersom det har gått 16 dager siden slutt-dato på tilfellet anser vi det som inaktivt og genererer ikke aktivitetskrav
Feilen funnet ifm https://jira.adeo.no/browse/FAGSYSTEM-345009:
Her ble det lest inn en person med oppfølgingstilfeller hvor det nyeste tilfellet startet i fremtiden. Dette ble filtrert bort og vi sjekket om det forrige oppfølgingstilfellet (med `fom` 6/8-2023 - `tom` 30/9-2023) skal generere aktivitetskrav. Siden dette hadde `antallSykedager = 56` (>= 8 uker) genererte det nytt aktivitetskrav selv om tilfellet ble avsluttet 30/9-2023.
Grunnen til at dette tilfellet ikke genererte aktivitetskrav ved tidligere innlesing er at vi har endret til å sjekke `antallSykedager` i stedet for antall dager mellom `fom` og `tom` (som i dette tilfellet ble 55 og < 8 uker)

IS-2658: Do not generate aktivitetskrav for inactive tilfelle

---

src/main/resources/db/migration/V5_3__delete_wrong_vurdering.sql

Sletter feilregistrert unntak og setter aktivitetskravet tilbake til status NY. Videre må veileder gjør ny vurdering for at det skal bli riktig i oversikten og hos eSyfo.
Ref: https://jira.adeo.no/browse/FAGSYSTEM-349036

IS-2724: Delete wrong unntak

---

src/main/kotlin/no/nav/syfo/application/api/ApiPlugins.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt

Dette er teknisk sett riktigere status-kode og gjør det enklere å håndtere feilen i frontend.

IS-2848: Respond 409 on conflict

---

src/main/resources/db/migration/V5_8__delete_wrong_vurdering.sql
src/main/resources/db/migration/V6_2__delete_wrong_vurdering.sql

- Litt usikker på hvordan dette skal håndteres.
Det som har skjedd:
- Satt opp aktivitetskrav og deretter vurdert `UNNTAK` som var feil. Har deretter startet ny aktivitetskravvurdering med riktig `AVVENT` vurdering. Lurer på om riktig løsning bare er å slette hele aktivitetskravet som har feil vurdering og flytte `previous_aktivitetskrav_uuid` og `referanse_tilfelle_bit_uuid` til det nyeste og riktige aktivitetskravet 🤔
Slik ser det ut i db👇
Jira-sak:
https://jira.adeo.no/browse/FAGSYSTEM-372631

IS-3172: Delete wrong unntak

---

src/main/kotlin/no/nav/syfo/infrastructure/client/dokarkiv/model/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt

Setter NAV_NO som distribusjonskanal etter avklaringer med Dokarkiv.
Se https://nav-it.slack.com/archives/C012X71FN04/p1751966666446009

IS-3363: Bruke NAV_NO som kanal ved journalforing
