.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
build.gradle.kts
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/BackgroundTask.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConsumerService.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaEnvironment.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaModule.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaTask.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonTask.kt
src/main/kotlin/no/nav/syfo/util/ObjectMapperConfig.kt

Logikk for prosessering kommer senere

Oppsett for å konsumere oppfølgingstilfeller kafka topic

---

build.gradle.kts

https://app.snyk.io/org/teamsykefravr/project/94ed2b20-0714-44e9-ba8f-7f25508e4d9f#issue-SNYK-JAVA-ORGAPACHECOMMONS-1316641

Overstyrer versjon av avhengighet for å fikse snyk issue

---

build.gradle.kts
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/api/ApiPlugins.kt
src/main/kotlin/no/nav/syfo/application/api/auth/ApiAuthenicationPlugin.kt
src/main/kotlin/no/nav/syfo/application/api/auth/JwtIssuer.kt
src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureAdTokenResponse.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureEnvironment.kt
src/main/kotlin/no/nav/syfo/client/wellknown/WellKnown.kt
src/main/kotlin/no/nav/syfo/client/wellknown/WellKnownClient.kt
src/main/kotlin/no/nav/syfo/client/wellknown/WellKnownDTO.kt
src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt
src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/JWTUtil.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/AzureADMock.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/MockServer.kt
src/test/resources/jwkset.json
src/test/resources/logback-test.xml

Mest oppsett av testkode og autentisering delvis copy-pasta fra andre apper. Implementasjon av GET og POST kommer i senere.

Setup veileder-api for aktivitetskrav

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVurderingService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaModule.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt

For å kunne vise knapper for å vurdere aktivitetskrav + historikk for person i Modia.

Veileder-API: Get aktivitetskrav-vurderinger for person

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml

For å kunne hente ut NAV-ident til veileder i vurder aktivitetskrav api-kallet

Add NAVident claim

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaModule.kt
src/main/kotlin/no/nav/syfo/client/ClientsEnvironment.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureAdClient.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureAdToken.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClientMetric.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlError.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlHentIdenterRequest.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlIdenterResponse.kt
src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
src/main/resources/pdl/hentIdenter.graphql
src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/PdlMock.kt

Skal brukes til å sjekke aktiv ident ved håndtering av identhendelse i senere PR.

Add pdl client

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Forbedret validering av status og årsaker ved opprettelse av vurdering

Add AktivitetskravStatus IKKE_OPPFYLT

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt

Beholder oppdatering av feltet i domene-laget slik at oppdatert verdi også sendes på Kafka.

Rename to updatedAt. Update from identhendelse.

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaAktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt

NB: Vent med å merge til syfooversiktsrv har endret til å bruke `sistVurdert`-felt på Kafka

Bruker updatedAt kun internt i db-laget

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

For å begrense data genererer vi ikke aktivitetskrav for oppfølgingstilfeller som startet før 1.2.2022.

Skip "old" oppfølgingstilfeller

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonTask.kt

Forsøk på å redusere kafka-feil ved konsumering av oppfølgingstilfeller i prod

Reduce poll size for oppfolgingstilfelleconsumer

---

.nais/naiserator-dev.yaml

Now it's the same as in syfooversiktsrv

Change cutoff date in dev

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjob.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/Cronjob.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobResult.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobRunner.kt
src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodClient.kt
src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodDTO.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

https://trello.com/c/9CS4qekm/1295-isaktivitetskrav-cronjob-for-%C3%A5-rydde-i-feilgenererte-aktivitetskrav

Setup automatisk oppfylt cronjob

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/resources/cronjob/uuids_ny.json

Merge når jeg jobben har kjørt i prod

Disable job and empty list

---

README.md
documentation/kafka/aktivitetskrav-vurdering.md

Datavarehus-gjengen ønsker seg dokumentasjon av det som finnes på kafka-topicen.
Veldig åpen for innspill på ting som kan forbedres her :)

Dokumentasjon av felter på aktivitetskrav-vurdering kafka-topic

---

src/main/resources/db/migration/V2_2__delete_wrong_vurdering.sql

https://jira.adeo.no/browse/FAGSYSTEM-270787

Delete vurdering made on wrong innbygger

---

documentation/kafka/aktivitetskrav-vurdering.md
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

For å kunne "vurdere" aktivitetskravet til de som ikke har sykepengerett (fjerne de fra oversikten).

Add status IKKE_AKTUELL

---

src/main/resources/db/migration/V2_4__delete_wrong_vurdering.sql

https://jira.adeo.no/browse/FAGSYSTEM-274276
Det er registrert en riktig vurdering etterpå så raden i aktivitetskrav trenger vi ikke oppdatere.

Slett feilregistrert vurdering

---

src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClientMetric.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlHentPersonRequest.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlPersonResponse.kt
src/main/resources/pdl/hentPerson.graphql
src/test/kotlin/no/nav/syfo/client/pdl/PdlClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/PdlMock.kt

Trengs til journalføring av forhåndsvarsel

Add navn() to PdlClient

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/client/ClientsEnvironment.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClient.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivMetric.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/AvsenderMottaker.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Bruker.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokument.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/DokumentInfo.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokumentvariant.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostResponse.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Sak.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Trenger denne til journalføring
Har også fått merget denne https://github.com/navikt/dokarkiv/pull/490

Add DokarkivClient

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/ArbeidstakervarselProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaArbeidstakervarselSerializer.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/PdfGenClient.kt
src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Publiserer forhåndsvarsel til arbeidstaker (via Kafka-topic)

Set up cronjob for publisering of forhandsvarsel

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
documentation/kafka/aktivitetskrav-vurdering.md
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjob.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Lukk alle aktivitetskrav med status NY og stoppunkt_at før 1.6.2023 (og etter arena-cutoff - ellers har de ikke oppgave i oversikten)

Høstdugnad

---

build.gradle.kts
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cache/RedisConfig.kt
src/main/kotlin/no/nav/syfo/application/cache/RedisStore.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClientMetric.kt
src/test/kotlin/no/nav/syfo/client/pdl/PdlClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/TestRedis.kt

Vi henter navn fra pdl når vi generer pdf og ved journalføring. Tenker derfor vi kan cache dette på samme måte som vi gjør i isdialogmote.

Cacher navn på person fra pdl

---

src/main/kotlin/no/nav/syfo/App.kt

Adds missing application thread pool config

Add missing application config

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt

- Refaktorerer fra å bruke `…Queries` filer som man kan kalle med en åpen database connection fra hele prosjektet til å bruke `…Repository` filer slik vi pratet om
- En endring som er verdt å nevne er at vi nå henter vurderingene til et aktivitetskrav hver gang vi henter et aktivitetskrav.
Gjenstår fortsatt en del, men dette er en start.

IS: Add repository to initialization of service

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/ExpiredVarsel.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt

- Legger til `UUID` til aktivitetskravet som varselet tilhører på `ExpiredVarsel` som blir publisert på `teamsykefravr.aktivitetskrav-expired-varsel` topicet. Dette konsumerer `ispersonoppgave` når den skal lage oppgave på et utgått varsel.

IS-1581: Add aktivietskravUuid on ExpiredVarsel

---

.nais/kafka/aktivitetskrav.yaml

ispersonoppgave skal lese Aktivitetskrav-vurderinger-topic

IS-1661: ispersonoppgave skal lese topic

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/ExpiredVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVarselProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/ExpiredVarselProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/ExpiredVarselSerializer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaAktivitetskravVarselSerializer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/KafkaAktivitetskravVurderingSerializer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/ExpiredVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PublishExpiredVarslerCronJobSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt

Oppdaget denne ved en tilfeldighet, fører også til litt import-endringer. 
❗ I dag er ExpiredVarsel både domeneobjekt og kafka-objekt, dette er kanskje ikke helt heldig? Ved store endringer på domeneobjektet vil dette gå ut over hva vi putter på topicet. Tanker?
EDIT: Det var flere kafka-objekter som lå "feil", så nå er alt lagt i en ny `kafka/domain`-mappe 👍🏼

IS: Fix package declaration for ExpiredVarsel

---

build.gradle.kts

Update dependencies (dependabot alerts)

Update dependencies (dependabot alerts)

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

- Legger til flere valg for når veileder bruker avvent for aktivitetskrav vurdering
- Se [tilhørende PR](https://github.com/navikt/syfomodiaperson/pull/1042) i `syfomodiaperson`

IS-1680: Add new arsak choices

---

documentation/kafka/aktivitetskrav-vurdering.md
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVarselProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt

Lagt til nytt felt for vurdering-uuid på kafka topics for aktivitetskrav-varsel og vurdering slik at eSyfo kan koble varsel til vurdering

IS-1720: Add vurdering-uuid to kafka topics for vurdering and varsel

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/client/ClientsEnvironment.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/Tilgang.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClientMetric.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/MockHttpClient.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/TilgangskontrollMock.kt

Bytte fra syfo-tilgangskontroll til istilgangskontroll

IS-1689: Use istilgangskontroll

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravStatus.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Trakk ut noe kode fra https://github.com/navikt/isaktivitetskrav/pull/148 og la til felt for om vurdering-status er final i dtoen slik at frontend kan begynne å bruke dette til å vise side for aktivitetskrav i sluttilstand.

IS-1676: Add final state flag to vurdering dto

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/AktivitetskravVurderingProducer.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/kafka/domain/KafkaAktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt

Aktivitetskrav.kt implementerer noen funksjoner i dag der den har et forhold til hvordan responsen fra API’et skal se ut, og hvordan melding som sender ut på kafka skal se ut.
Flytter disse funksjonene til å importere Aktivitetskrav.kt  slik at domenelaget bedre isoleres 😊

IS-1792: Refactor

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PublishExpiredVarslerCronJobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt

Samlet kode for å opprette et aktivitetskrav i AktivitetskravRepository. Sletter samtidig query og funksjon fra AktivitetskravVurderingQueries.

IS-1783: Create aktivitetskrav in repository only

---

src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApplicationEngineUtils.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Fikk et behov for å refaktorere testene og dele opp AktivitetskravApiSpek, så gjør det i en egen PR. Tilpasninger relatert til tilstandsendringer kommer etterpå.

Refactor tests

---

src/main/kotlin/no/nav/syfo/App.kt

- Fikser deploy issues for https://github.com/navikt/isaktivitetskrav/pull/168
- Linje 107 i `App.kt` prøvde å bruke `applicationDatabase` før den ble initialisert på 116-118.
- Deployer fint til dev https://github.com/navikt/isaktivitetskrav/actions/runs/6864758611

IS: Fix deploy issue

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravStatus.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/application/api/ApiPlugins.kt
src/main/kotlin/no/nav/syfo/application/exception/ConflictException.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt

Validere tilstandsendringer for vurdering av aktivitetskrav

IS-1663: Validere tilstandsendringer

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/HistorikkDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/PAktivitetskrav.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/Aktivitetskrav.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestRedis.kt

Jobber videre med en test for dette

IS-1878: Historikk

---

build.gradle.kts

Upgrade deps

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaOppfolgingstilfellePersonGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/OppfolgingstilfelleGenerator.kt

Bruker antall sykedager til å regne ut antall uker i stedet for fra/til på oppfølgingstilfellet.

IS-1861: Use antall sykedager

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVurderingQueries.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt

Flyttet flere database-operasjoner til `AktivitetskravRepository` og fjerner direkte avhengighet til database i `AktivitetskravService`.

Refactor: Move more queries to AktivitetskravRepository

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/VarselPdfService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/VarselType.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokument.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/ForhandsvarselPdfDTO.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/PdfGenClient.kt
src/main/kotlin/no/nav/syfo/client/pdfgen/VurderingPdfDTO.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/client/pdfgen/PdfGenClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/ForhandsvarselGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/PdfGenClientMock.kt

Lagt til UNNTAK varseltype og implementert kall til pdfgen for det.
Gjenstår å lage varsel og pdf i `AktivitetskravService` ved vurdering og tilpasse api til å motta document-tekster fra frontend.

IS-1904: Add varseltype unntak and implement pdfgen call

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingRequestDTO.kt

Slik at frontend kan sende document for vurdering som skal journalføres.

IS-1904: Add document to vurdering request

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravVarselRepository.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravStatus.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVarsel.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravAutomatiskOppfyltCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/AktivitetskravNyCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PublishExpiredVarslerCronJobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

Oppretter varsel og pdf for unntak-vurdering. Journalføres og publiseres på varsel-topic via cronjob.

IS-1904: Create varsel with document and pdf for unntak

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/VarselPdfService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/AktivitetskravStatus.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/VarselType.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt

Legger til varseltyper for vurderingene `OPPFYLT` og `IKKE_AKTUELL` og oppretter varsel og pdf til journalføring for disse.
Merge etter https://github.com/navikt/syfomodiaperson/pull/1134

IS-1904: Create varsel and pdf for oppfylt and ikke aktuell

---

src/main/resources/db/migration/V3_9__delete_wrong_vurdering.sql

Se jirasak https://jira.adeo.no/browse/FAGSYSTEM-310227

Delete vurdering and set aktivitetskravstatus to previous vurderingstatus

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt

Dette er ikke påkrevd felt i https://confluence.adeo.no/display/BOA/opprettJournalpost. Siden vi heller ikke vet hvordan (eller om) journalposten distribueres videre blir det nok mest riktig å sette den til null.

IS-1604: Ikke sett kanal på JP

---

src/main/resources/db/migration/V4_1__delete_wrong_vurdering.sql

https://jira.adeo.no/browse/FAGSYSTEM-314437
Trenger vi å be esyfo gjøre noe i aktivitetskrav-backend i tillegg?

IS-2010: Slett feilregistrert unntak

---

src/main/resources/db/migration/V4_3__delete_wrong_vurdering.sql

Ref https://jira.adeo.no/browse/FAGSYSTEM-314696

IS-2029: Slett feilregistrert unntak

---

build.gradle.kts

Bump postgres and other dependencies

---

src/main/resources/db/migration/V4_5__delete_wrong_vurdering.sql

Det er startet ny vurdering og satt unntak med riktig tekst etterpå så trengs ingen rydding utover dette :relieved:

IS-2118: Delete unntak vurdering with wrong text

---

src/main/resources/db/migration/V4_6__delete_wrong_vurdering.sql

Se jira-sak: https://jira.adeo.no/browse/FAGSYSTEM-323577

IS-2224: Delete vurdering

---

.github/workflows/alerts.yaml
.github/workflows/codeql.yaml
.github/workflows/dependency-submission.yaml
.github/workflows/kafka-aktivitetskrav.yaml

Endrer til at vi bruker `main` som hovedbranch

IS: Change to use main as primary branch

---

src/main/resources/db/migration/V4_7__delete_wrong_vurdering.sql

Se Jira-sak https://jira.adeo.no/browse/FAGSYSTEM-337995

IS-2519: Delete wrong vurdering

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml

- Add `syfooversiktsrv` to inbound list

IS-2329: Add syfooversiktsrv to inbound

---

src/main/resources/db/migration/V4_9__delete_wrong_vurdering.sql

- Sletter vurdering gjort på feil person

IS-2570: Delete wrong vurdering

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt

Ikke sette mottaker på journalpost når typen er NOTAT.

IS-2670: Null ut jp-mottaker for notat

---

src/main/resources/db/migration/V5_1__delete_wrong_vurdering.sql

Sletter bare selve vurderingen her siden veileder allerede har startet en ny vurdering for registrere unntak med riktig tekst.

IS-2682: Slette feilregistrert vurdering

---

src/main/resources/db/migration/V5_2__delete_wrong_vurdering.sql

- Sletter aktivitetskrav gjort på feil person.

IS-2692: Delete wrong vurdering

---

README.md

Endret java versjon fra 17 til 21 i readme

edit java version readme

---

src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseService.kt
src/main/kotlin/no/nav/syfo/infrastructure/pdl/PdlClient.kt

Vi har endret til warn i de fleste andre apper for lenge siden. Denne dukker stadig opp i loggene, så tenkte jeg kunne fikse siden jeg var agent. Det er som regel timing-issues, så vi prøver på nytt etter 1 minutt.

IS: Change log-level from error to warning for identhendelse

---

src/main/resources/db/migration/V5_4__delete_wrong_vurdering.sql

Ref: https://jira.adeo.no/browse/FAGSYSTEM-351518
Det er gjort riktig vurdering (OPPFYLT) etterpå så det er tilstrekkelig å bare slette unntak-vurderingen.

IS-2746: Delete wrong unntak

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cache/RedisConfig.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Bytter til felles-cache'n. Denne app'en har brukt Aiven-cache fra før.

IS-2765: Bruke felles Aiven-cache

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/ForhandsvarselDTO.kt
src/main/kotlin/no/nav/syfo/domain/AktivitetskravVarsel.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiForhandsvarselSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/ForhandsvarselGenerator.kt

Bruker fristdato som sendes med i DTO fra klienten (syfomodiaperson) i stedet for å beregne den (på nytt) her i backend'en.
Må merges etter https://github.com/navikt/syfomodiaperson/pull/1544

IS-2817: Utvidet frist jul

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Disable journalføring i dev-gcp

IS-2643: Disable journalføring i dev

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjob.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Skrur igjen på journalføring i dev-gcp, men gjør ikke retry når det feiler.

IS-2643: Turn off retry of journalforing in dev

---

src/main/resources/db/migration/V5_5__delete_wrong_vurdering.sql

- Sletter vurdering som er gjort på feil person

IS-2990: Delete wrong vurdering

---

src/main/resources/db/migration/V5_6__delete_wrong_vurdering.sql

Ref: https://jira.adeo.no/browse/FAGSYSTEM-366339

IS-3038: Delete wrong vurdering

---

.nais/kafka/aktivitetskrav.yaml

Appen leser ikke lenger topicen så kan fjerne denne

Remove ispersonoppgave from topic access

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravVarselService.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApi.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravResponseDTO.kt
src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingRequestDTO.kt
src/main/kotlin/no/nav/syfo/domain/AktivitetskravStatus.kt
src/main/kotlin/no/nav/syfo/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/AktivitetskravRepository.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/AktivitetskravVurderingQueries.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PAktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/kafka/domain/AktivitetskravVurderingRecord.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

- Prøver å refaktorere `AktivitetskravVurdering` slik at vurderingsklassene gjenspeiler hva som faktisk kreves når man gjør vurderingen.
- Her er det mye mer man kan gjøre så det får bli oppfølging.
- Har testet i dev og det ser ut som det flyr der.

IS: Refactor AktivitetskravVurdering domain class

---

src/main/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravVurderingRequestDTO.kt
src/main/kotlin/no/nav/syfo/domain/AktivitetskravVurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PAktivitetskravVurdering.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravServiceSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/AktivitetskravSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/api/AktivitetskravApiVurderSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/JournalforAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/OutdatedAktivitetskravCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/cronjob/PubliserAktivitetskravVarselCronjobSpek.kt
src/test/kotlin/no/nav/syfo/aktivitetskrav/database/AktivitetskravRepositorySpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/AktivitetskravGenerator.kt

- Oppfølgende refactor som følge av [denne kommentaren](https://github.com/navikt/isaktivitetskrav/pull/291#discussion_r1975293189) på forrige PR.
- Fjerner `VurderingArsak` som nå er unødvendig ettersom årsakstypene ligger innad i hver vurdering. Ser også i forrige PR at jeg ikke helt fulgte konvensjon på navn på `enum class`.

IS: Refactor remove VurderingArsak

---

src/main/resources/db/migration/V5_8__trigger_revarsel_forhandsvarsel.sql

Ref prodfeil om forhåndsvarsler som ikke har blitt varslet.

IS-3178: Trigger revarsel of forhandsvarsler

---

src/main/resources/db/migration/V6_3__delete_wrong_vurdering.sql

Løser to jira-saker: FAGSYSTEM-380337 og FAGSYSTEM-380204

IS-3270: Slette feilregistrerte vurderinger

---

src/main/resources/db/migration/V6_4__analyze.sql

Skal merges etter at oppgraderingen av databasen er ferdig

IS-3251: Oppdater statistikk etter migrering til Postgres 17

---

src/main/resources/db/migration/V6_5__delete_wrong_vurdering.sql

Sletter aktivitetskrav med feilregistrert vurdering
https://jira.adeo.no/browse/FAGSYSTEM-388316

IS-3359: Slette feilregistrert vurdering
